name: Build and Upload Image

on:
  workflow_dispatch:
    inputs:
      id:
        description: "Run Identifier"
        required: true

env:
  DOCKER: northamerica-northeast1-docker.pkg.dev
  AR_PATH: frontside-backstage/frontside-artifacts/podinfo

jobs:
  build-and-upload:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - name: ${{ github.event.inputs.id }}
        run: echo "Workflow run identifier:" ${{ github.event.inputs.id }}
      - uses: actions/checkout@v3
      - name: Google Cloud Workload Identity Federation
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.HUMAN_CLOUD_PROVIDER }} # 🚨 cloud_workload_provider
          service_account: ${{ secrets.HUMAN_CLOUD_SERVICE }} # 🚨 cloud_service_account
      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Authenticate to Artifacts Registry
        run: gcloud auth configure-docker $DOCKER
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER }}/${{ env.AR_PATH }}:${{ github.event.inputs.id }}
